openapi: 3.0.0
info:
  title: Natasha Chatbot API
  description: Minimal semantic actions for Natasha AI chatbot
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local MFE Shell server

paths:
  /semantic-actions/navigateToProducts:
    post:
      operationId: navigateToProducts
      summary: Navigate to products page
      description: Navigate to products page when user asks to see products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userQuery:
                  type: string
                  example: "show me products"
      responses:
        "200":
          description: Navigation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
                    example: "navigation"
                  target:
                    type: string
                    example: "/products"
                  message:
                    type: string
                    example: "Navigating to products page"

  /semantic-actions/navigateToOrders:
    post:
      operationId: navigateToOrders
      summary: Navigate to orders page
      description: Navigate to orders page when user asks to see orders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userQuery:
                  type: string
                  example: "show me my orders"
      responses:
        "200":
          description: Navigation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
                    example: "navigation"
                  target:
                    type: string
                    example: "/orders"
                  message:
                    type: string
                    example: "Navigating to orders page"

  /semantic-actions/showUserProfile:
    post:
      operationId: showUserProfile
      summary: Show user profile
      description: Show user profile information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userQuery:
                  type: string
                  example: "show my profile"
      responses:
        "200":
          description: Profile information retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
                    example: "display_info"
                  target:
                    type: string
                    example: "user_profile"
                  message:
                    type: string
                    example: "Here's your profile information"

# OpenAI Configuration
x-openai-config:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 150

x-system-prompt: |
  You are Natasha, a helpful AI assistant for an e-commerce application. 
  You can help users navigate to products, orders, and show their profile.
  Keep responses concise and friendly.
